language: bash

services:
  - docker

group: bluezone

dist: xenial

sudo: required
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
        key_url: 'https://download.docker.com/linux/ubuntu/gpg'
    packages:
      - docker-ce
      
before_install:
  - echo "Killing auto-updates to avoid apt lock conflicts";
  - sudo systemctl stop apt-daily.service;
  - sudo systemctl stop apt-daily.timer;
  - sudo systemctl stop apt-daily-upgrade.service;
  - sudo systemctl stop apt-daily-upgrade.timer;
  - bash .travis/waitForAptStop.sh
  - if [ "$TRAVIS_OS_NAME" = "linux-s390" ]; then
      sudo apt-get install -y unzip wget;
    fi
  - sudo apt-get install -y dnsutils
  - sudo chgrp travis /var/run/docker.sock
  - docker version

jobs:
  include:
    - stage: build-push-images
      os: linux
      script:
      - uname -a
      - cat /etc/issue
      - ./build.sh
