apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: loyalty-level
    solution: stock-trader
  name: loyalty-level
  namespace: stock-trader
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: loyalty-level-service
    weight: 100
  wildcardPolicy: None
