apiVersion: v1
kind: Service
metadata:
  name: kappnav-api-service
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/component: kappnav-ui
